#!/usr/bin/env python

from argumentos import args
import yaml
from secuencia import Secuencia
from midiutil import MIDIFile

defs = []
for archivo in args.archivos:
  data = open( archivo.name, 'r' )
  try:
    y = yaml.load( data, Loader = yaml.FullLoader ) 
    defs.append( y )
  except Exception as e:
    print( e )
    print( "=" * 80 )

secuencia = Secuencia( defs )

midi_tracks = MIDIFile( len( secuencia.pistas ) )

for evento in secuencia.eventos:
  # evento puede ser un dic: nombredefuncion, args
  getattr( midi_tracks, evento[0] )( *evento[1:] )

with open( args.output + ".mid", "wb" ) as archivo_midi:
   midi_tracks.writeFile( archivo_midi )

# https://setuptools.readthedocs.io/en/latest/setuptools.html
# https://stackoverflow.com/questions/1471994/what-is-setup-py
