#!/usr/bin/env python
from argumentos import args
from main import EVENTOS, formato_tiempo
from pista import Pista
from midiutil import MIDIFile

"""
 Salida MIDI
"""
nombre_archivo = args.output
pistas_cantidad = Pista.cantidad 
midi_tracks = MIDIFile( pistas_cantidad ) 
for m in EVENTOS:
    mu = getattr( midi_tracks, m[0] )( *m[1:] )
with open( nombre_archivo + ".mid", "wb" ) as archivo_midi:
   midi_tracks.writeFile( archivo_midi )


"""
TO DO:
    [ ] revisar metro
    [ ] pasar intervalos a propiedad de segmento/unidad
    [x] terminar midiUTIL 
    [x] Agregar: Segmento (grupo de articulaciones) 
       [ ] parametros de Segmento = art#0 de la unidad
    [ ] Excepciones main
    [ ] Agregar: Registro 
    [ ] YAML validation 
    [ ] Revisar diferentes tempos en diferentes traks
"""
